name: my first workflow.

on:
 push:
  branches: 
    - "*"

jobs:
  first_workflow:
     runs-on: ubuntu-latest
     steps:
      - name: Hello this is my first workflow
        run: echo "My first work flow"

      - name: Print user name
        run: echo "my name is $USER"
